### ISSUE TITLE
renderElement callback

### ISSUE THREAD

**Issue by DanielMaass** [marsprince/slate-vue#69]
Hey marsprince,
I have some questions to the renderElement callback from Editable component:

1. In the slate js docu are props listed like parent and editor. Unfortunately I get only { attributes, children, element }. I want to pass a property from the parent node to my rendered component. Did I miss something or are these properties not implemented yet? Is there a workaround to get the props from parent node?

2. I thought the attributes of the current node/element are stored in the props.attributes and can easily be assigned to the corresponding component using {...{attrs: props.attributes}}. Unfortunately I only get {data-slate-node: "element"}. The attributes I am looking for can only be found in props.element. Is that correct? That means I have to add the desired attributes for each component myself, right?

Many, many thanks for the Slate-Vue plugin. I hope it will be great. :) And thanks also for your effort .
Daniel

**Comment by marsprince** [comment]
You are right. RenderElement functions's props are designed as { attributes, children, element } in order to be consistent with Slate-react. Code here:
https://github.com/marsprince/slate-vue/blob/master/packages/slate-vue/components/element.tsx#L112

And you can see the reasons In Slate.js docs:
https://docs.slatejs.org/concepts/08-rendering

> 🤖 Be sure to mix in props.attributes and render props.children in your custom components! The attributes must be added to the top-level DOM element inside the component, as they are required for Slate's DOM helper functions to work. And the children are the actual text content of your document which Slate manages for you automatically.

Attributes and children are all internal based on my understanding of Slate.js. And element is current node. 

All rendering process of ELEMENT component (props and attributes) are implemented by  Slate-vue or Slate-react. So I don't catch your point about passing props and attributes to children. Can you provide more information about your design or code?
